import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

function readRepoFile(relativePath) {
  return readFileSync(resolve(process.cwd(), relativePath), 'utf8');
}

test('settings expose a Help launcher', () => {
  const html = readRepoFile('apps/web/index.html');
  assert.match(html, /id="settings-open-help"/);
  assert.match(html, />Help</);
  assert.match(html, /Browse BrianHub documentation, including the API reference/i);
});

test('in-app help page is a documentation hub with API navigation', () => {
  const html = readRepoFile('apps/web/index.html');
  assert.match(html, /id="help-page"/);
  assert.match(html, /<h2>Help &amp; Documentation<\/h2>/);
  assert.match(html, /Documentation home/);
  assert.match(html, /API documentation/);
  assert.match(html, /id="help-open-url"/);
  assert.match(html, /id="help-api-url"/);
});

test('dedicated API help page exists at its own URL path and is plain-text oriented', () => {
  const html = readRepoFile('apps/web/help/api/index.html');
  assert.match(html, /<title>BrianHub API Help<\/title>/);
  assert.match(html, /id="api-help-copy"/);
  assert.match(html, /<pre id="api-help-doc" class="api-help-doc"/);
  assert.match(html, /\/apps\/web\/help\/api\//);
  assert.match(html, /Single-column markdown reference for implementing the BrianHub product API/i);
  assert.doesNotMatch(html, /api-help-meta/);
});

test('shared BrianHub API docs module documents the current resource model', () => {
  const script = readRepoFile('apps/web/help/api-docs.js');
  assert.match(script, /export const BRIANHUB_API_HELP_PATH = '\/apps\/web\/help\/api\/';/);
  assert.match(script, /group_label/);
  assert.match(script, /Do not model sections as parent tasks or subtasks/);
  assert.match(script, /GET \/shopping-lists\?workspace_id=<uuid>/);
  assert.match(script, /scheduled_for/);
  assert.match(script, /POST \/tasks\/:id\/convert-to-shopping-item/);
  assert.match(script, /GET \/agent-events\?workspace_id=<uuid>/);
  assert.match(script, /PATCH \/agent-events\/:id/);
  assert.match(script, /service_account_auth: available-v1/);
  assert.match(script, /Authorization: Bearer <token>/);
  assert.match(script, /GET \/admin\/service-accounts/);
  assert.match(script, /POST \/admin\/service-accounts\/:id\/tokens/);
  assert.match(script, /GET \/admin\/service-accounts\/:id\/activity/);
  assert.match(script, /telegram_group/);
  assert.match(script, /tasks\.delete/);
  assert.match(script, /GET \/projects\?workspace_id=<uuid>/);
  assert.match(script, /GET \/notice-types\?workspace_id=<uuid>/);
  assert.match(script, /POST \/sync\/pull/);
  assert.match(script, /principal_type/);
});

test('app wiring opens the in-app help hub and the dedicated API help url', () => {
  const script = readRepoFile('apps/web/app.js');
  assert.match(script, /import \{ buildBrianhubApiHelpUrl \} from '\.\/help\/api-docs\.js';/);
  assert.match(script, /function openBrianhubApiHelpPage\(\)/);
  assert.match(script, /window\.location\.assign\(buildBrianhubApiHelpUrl\(window\.location\.origin\)\);/);
  assert.match(script, /settingsOpenHelp\?\.addEventListener\('click', \(\) => \{\s*openSettingsLinkedPage\('help'\);/);
  assert.match(script, /helpOpenUrl\?\.addEventListener\('click', openBrianhubApiHelpPage\);/);
  assert.match(script, /helpApiUrl\.textContent = helpUrl;/);
});

test('admin console exposes service-worker, token, and workspace-grant controls', () => {
  const html = readRepoFile('apps/web/index.html');
  assert.match(html, /id="admin-invites-summary"/);
  assert.match(html, /id="admin-users-search"/);
  assert.match(html, /id="admin-users-summary"/);
  assert.match(html, /id="admin-user-summary"/);
  assert.match(html, /<h3>Service workers<\/h3>/);
  assert.match(html, /id="admin-service-accounts-search"/);
  assert.match(html, /Search workers by name, alias, or description/);
  assert.match(html, /id="admin-service-accounts-filter"/);
  assert.match(html, /<option value="attention">Needs attention<\/option>/);
  assert.match(html, /id="admin-service-accounts-summary"/);
  assert.match(html, /id="admin-service-account-roger-preset"/);
  assert.match(html, /id="admin-service-summary-name"/);
  assert.match(html, /id="admin-service-summary-stats"/);
  assert.match(html, /id="admin-service-setup-note"/);
  assert.match(html, /id="admin-service-setup-checklist"/);
  assert.match(html, /id="admin-service-account-permissions"/);
  assert.match(html, /<h4>Worker identity &amp; baseline access<\/h4>/);
  assert.match(html, /<h4>Tokens<\/h4>/);
  assert.match(html, /id="admin-service-token-state"/);
  assert.match(html, /id="admin-service-token-mode-issue"/);
  assert.match(html, /id="admin-service-token-mode-manage"/);
  assert.match(html, /id="admin-service-token-editor-title"/);
  assert.match(html, /id="admin-service-token-editor-meta"/);
  assert.match(html, /id="admin-service-token-inherit"/);
  assert.match(html, /id="admin-service-token-reveal"/);
  assert.match(html, /id="admin-service-token-acknowledge"/);
  assert.match(html, /id="admin-service-token-list-summary"/);
  assert.match(html, /id="admin-service-token-create-actions"/);
  assert.match(html, /id="admin-service-token-manage-actions"/);
  assert.match(html, /<h4>Workspace access<\/h4>/);
  assert.match(html, /id="admin-service-grant-workspace"/);
  assert.match(html, /id="admin-service-grants-summary"/);
  assert.match(html, /id="admin-service-effective-workspaces"/);
  assert.match(html, /id="admin-service-grants-list"/);
  assert.match(html, /<h4>Activity<\/h4>/);
  assert.match(html, /id="admin-service-activity-refresh"/);
  assert.match(html, /id="admin-service-activity-summary"/);
  assert.match(html, /id="admin-service-activity-filters"/);
  assert.match(html, /id="admin-service-activity-highlights"/);
  assert.match(html, /id="admin-service-activity-list"/);
});

test('admin console wiring includes service-account API helpers and event handlers', () => {
  const apiScript = readRepoFile('apps/web/api.js');
  assert.match(apiScript, /export function listAdminServiceAccounts/);
  assert.match(apiScript, /export function createAdminServiceAccountToken/);
  assert.match(apiScript, /export function deleteAdminServiceAccountWorkspaceGrant/);
  assert.match(apiScript, /export function listAdminServiceAccountActivity/);

  const appScript = readRepoFile('apps/web/app.js');
  assert.match(appScript, /async function refreshAdminServiceAccounts/);
  assert.match(appScript, /async function createAdminServiceToken/);
  assert.match(appScript, /async function addAdminServiceWorkspaceGrant/);
  assert.match(appScript, /async function refreshAdminServiceAccountActivity/);
  assert.match(appScript, /function renderAdminServiceAccountSummary/);
  assert.match(appScript, /function getServiceWorkerReadinessState\(account\)/);
  assert.match(appScript, /function renderAdminServiceActivityList/);
  assert.match(appScript, /function setAdminServiceTokenState/);
  assert.match(appScript, /function setAdminServiceTokenListSummary/);
  assert.match(appScript, /function setAdminServiceTokenEditorMeta/);
  assert.match(appScript, /function setAdminInvitesSummary\(message = ''\)/);
  assert.match(appScript, /function setAdminUsersSummary\(message = ''\)/);
  assert.match(appScript, /function setAdminUserSummary\(message = ''\)/);
  assert.match(appScript, /function setAdminServiceAccountsSummary\(message = ''\)/);
  assert.match(appScript, /function setAdminServiceActivitySummary\(message = ''\)/);
  assert.match(appScript, /function getAdminUserServiceAccounts\(user\)/);
  assert.match(appScript, /function getAdminUserServiceWorkerSummary\(user\)/);
  assert.match(appScript, /function getAdminUsersSearchQuery\(\)/);
  assert.match(appScript, /function getFilteredAdminUsers\(\)/);
  assert.match(appScript, /function getAdminServiceAccountsSearchQuery\(\)/);
  assert.match(appScript, /function getAdminServiceAccountsReadinessFilter\(\)/);
  assert.match(appScript, /function getFilteredAdminServiceAccounts\(\)/);
  assert.match(appScript, /function getServiceWorkerAttentionState\(account\)/);
  assert.match(appScript, /function getAdminGrantableOrganizationSurfaceWorkspaces\(orgId = getAdminOrgId\(\)\)/);
  assert.match(appScript, /function isAdminServiceTokenExpiringSoon\(token, thresholdDays = 7\)/);
  assert.match(appScript, /function compareAdminServiceTokens\(left, right\)/);
  assert.match(appScript, /function getAdminServiceWorkspaceScopeLabel\(workspace, \{ short = false \} = \{\}\)/);
  assert.match(appScript, /function getAdminServiceWorkspaceScopeTone\(workspace\)/);
  assert.match(appScript, /function formatAdminServiceWorkspaceOptionLabel\(workspace\)/);
  assert.match(appScript, /function getAdminServiceWorkspaceScopeCounts\(workspaces = \[\]\)/);
  assert.match(appScript, /function findAdminServiceWorkspaceRecord\(workspaceId\)/);
  assert.match(appScript, /function setAdminServiceGrantsSummary\(message = ''\)/);
  assert.match(appScript, /function normalizeAdminServiceActivityFilter\(filter\)/);
  assert.match(appScript, /function getServiceAccountActivityCategory\(event\)/);
  assert.match(appScript, /function buildAdminServiceActivityFilterOptions\(events = \[\]\)/);
  assert.match(appScript, /function buildAdminServiceActivityHighlights\(events = \[\]\)/);
  assert.match(appScript, /function buildAdminServiceActivityOperationalStatus\(selectedAccount, events = \[\]\)/);
  assert.match(appScript, /function normalizeAdminServiceTokenEditorMode\(mode\)/);
  assert.match(appScript, /function getAdminServiceTokenEditorMode\(\)/);
  assert.match(appScript, /function setAdminServiceTokenEditorMode\(mode\)/);
  assert.match(appScript, /function buildAdminServiceTokenPayload/);
  assert.match(appScript, /function formatApiTokenTone\(status\)/);
  assert.match(appScript, /function getServiceWorkerTokenAccessLabel\(token\)/);
  assert.match(appScript, /function selectAdminServiceToken\(tokenId, \{ requireConfirm = true \} = \{\}\)/);
  assert.match(appScript, /function focusAdminServiceSetupTarget\(target\)/);
  assert.match(appScript, /function buildAdminServiceSetupSteps\(/);
  assert.match(appScript, /function presentAdminServiceToken\(rawToken, actionLabel = 'created'\)/);
  assert.match(appScript, /function confirmAbandonPendingAdminServiceTokenReveal\(/);
  assert.match(appScript, /function acknowledgeAdminServiceTokenReveal\(/);
  assert.match(appScript, /window\.addEventListener\('beforeunload', \(event\) => \{/);
  assert.match(appScript, /adminServiceTokenAcknowledge\?\.addEventListener\('click', \(\) => \{/);
  assert.match(appScript, /rotateBtn\.textContent = 'Regenerate';/);
  assert.match(appScript, /revokeBtn\.textContent = 'Revoke';/);
  assert.match(appScript, /void refreshAdminServiceAccounts\(\);/);
  assert.match(appScript, /adminServiceAccountRogerPreset\?\.addEventListener\('click'/);
  assert.match(appScript, /adminServiceTokenModeIssue\?\.addEventListener\('click'/);
  assert.match(appScript, /adminServiceTokenModeManage\?\.addEventListener\('click'/);
  assert.match(appScript, /adminServiceTokenRotate\?\.addEventListener\('click'/);
  assert.match(appScript, /adminServiceGrantAdd\?\.addEventListener\('click'/);
  assert.match(appScript, /adminServiceActivityRefresh\?\.addEventListener\('click'/);
  assert.match(appScript, /adminUsersSearch\?\.addEventListener\('input'/);
  assert.match(appScript, /adminServiceAccountsSearch\?\.addEventListener\('input'/);
  assert.match(appScript, /adminServiceAccountsFilter\?\.addEventListener\('change'/);
  assert.match(appScript, /Step 1 of 3: save the worker/);
  assert.match(appScript, /Step 2 of 3: save is complete\. Next, grant the workspace this worker should access\./);
  assert.match(appScript, /Step 3 of 3: workspace access is ready, but this worker is still inert until you generate or regenerate an active token\./);
  assert.match(appScript, /Ready: this worker has workspace access and at least one active token\./);
  assert.match(appScript, /Save worker identity/);
  assert.match(appScript, /Grant workspace access/);
  assert.match(appScript, /Generate an active token/);
});

test('admin console auto-selects existing service accounts and surfaces summary counts', () => {
  const appScript = readRepoFile('apps/web/app.js');
  assert.match(appScript, /function getAdminOrgId\(\)\s*\{\s*return getAuthState\(\)\.user\?\.org_id \?\? DEFAULT_ORG_ID;\s*\}/);
  assert.match(appScript, /function normalizeServiceAccountSummary\(/);
  assert.match(appScript, /function getVisibleAdminServiceAccounts\(\)/);
  assert.match(appScript, /created_by_user_id: account\.created_by_user_id \? String\(account\.created_by_user_id\)\.trim\(\) : ''/);
  assert.match(appScript, /return accounts\.filter\(\(account\) => String\(account\.created_by_user_id \?\? ''\)\.trim\(\) === selectedUser\.id\);/);
  assert.match(appScript, /function syncAdminServiceAccountSelectionForUser\(\)/);
  assert.match(appScript, /function resetAdminServiceAccountDetailState\(/);
  assert.match(appScript, /summary\.active_token_count/);
  assert.match(appScript, /summary\.effective_workspace_count/);
  assert.match(appScript, /visibleAccounts\.length\)\s*\{\s*adminState\.selectedServiceAccountId = visibleAccounts\[0\]\?\.id \?\? '';/);
  assert.match(appScript, /No service workers for \$\{selectedUser\.email \?\? selectedUser\.display_name \?\? 'this user'\} yet\./);
  assert.match(appScript, /refreshAdminServiceAccountActivity\(\)/);
  assert.match(appScript, /This worker has no tokens yet and cannot connect to BrianHub until you generate its first token\./);
  assert.match(appScript, /No pending invites\. Fresh invite links will appear here until they are accepted or deleted\./);
  assert.match(appScript, /No users match “\$\{query\}”\./);
  assert.match(appScript, /setAdminInvitesSummary\(summaryParts\.join\(' • '\)\);/);
  assert.match(appScript, /setAdminUsersSummary\(summaryParts\.join\(' • '\)\);/);
  assert.match(appScript, /setAdminUserSummary\(summaryParts\.join\(' • '\)\);/);
  assert.match(appScript, /setAdminServiceAccountsSummary\(summaryParts\.join\(' • '\)\);/);
  assert.match(appScript, /setAdminServiceGrantsSummary\(summaryParts\.join\(' • '\)\);/);
  assert.match(appScript, /setAdminServiceActivitySummary\(summaryParts\.join\(' • '\)\);/);
  assert.match(appScript, /No service workers match the current search\/filter\./);
  assert.match(appScript, /if \(readinessFilter === 'attention'\) \{/);
  assert.match(appScript, /summaryParts\.push\(`\$\{attentionCount\} need review`\);/);
  assert.match(appScript, /badges\.appendChild\(createAdminServiceChip\(attention\.label, attention\.tone\)\);/);
  assert.match(appScript, /getAdminGrantableOrganizationSurfaceWorkspaces\(orgId\)/);
  assert.match(appScript, /option\.textContent = formatAdminServiceWorkspaceOptionLabel\(workspace\);/);
  assert.match(appScript, /`\$\{workspace\.name \|\| workspace\.id\} · \$\{getAdminServiceWorkspaceScopeLabel\(workspace, \{ short: true \}\)\}`/);
  assert.match(appScript, /badges\.appendChild\(createAdminServiceChip\(effective \? 'Effective now' : 'Inactive', effective \? 'success' : 'warning'\)\);/);
  assert.match(appScript, /metaParts\.push\(\s*workerSummary\.total/);
  assert.match(appScript, /renderAdminUsersList\(\);\s*renderAdminUserEditor\(\);\s*renderAdminServiceAccountsList\(\);/);
  assert.match(appScript, /const tokens = \[\.\.\.adminState\.serviceAccountTokens\]\.sort\(compareAdminServiceTokens\);/);
  assert.match(appScript, /badges\.appendChild\(createAdminServiceChip\('Never used', 'muted'\)\);/);
  assert.match(appScript, /badges\.appendChild\(createAdminServiceChip\('Superseded', 'warning'\)\);/);
  assert.match(appScript, /buildAdminServiceActivityFilterOptions\(activityEvents\)\.forEach\(\(option\) => \{/);
  assert.match(appScript, /button\.textContent = `\$\{option\.label\} · \$\{option\.count\}`;/);
  assert.match(appScript, /setAdminServiceActivityFilter\(option\.key\);/);
  assert.match(appScript, /buildAdminServiceActivityHighlights\(activityEvents\)\.forEach\(\(highlight\) => \{/);
  assert.match(appScript, /setAdminServiceActivityStatus\(activityStatus\.message, activityStatus\.tone\);/);
});
